on:
  - [push, pull_request]

name: test
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0
      - name: test
        run: bun test
